# ZSH-specific
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="awesomepanda"

# Command auto-correction.
ENABLE_CORRECTION="true"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# User configuration
# Environment variables
export EDITOR='vim'
export BROWSER='google-chrome-stable'
export SSH_KEY_PATH="~/.ssh/id_rsa"
export CSCOPE_EDITOR=vim
export DOTFILES=$HOME/projects/dotfiles
export WORKSPACE=$HOME/projects
#export DISPLAY=:0.0

# Other configurations
# 10ms for key sequences
KEYTIMEOUT=1

# For fixed tmux title
DISABLE_AUTO_TITLE="true"

# Python Virtual Environment
# export WORKON_HOME=~/.virtualenvs
# export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
# export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv
# [[ -a /usr/bin/virtualenvwrapper.sh ]] && source /usr/bin/virtualenvwrapper.sh

# Shortcut
alias vimrc="vim $HOME/.vimrc"
alias rr="source ~/.zshrc"
alias zshrc="vim $HOME/.zshrc"

# Load all files in ~/.zsh
for fn in $HOME/.zsh/*; do
  source $fn
done

export RDM=/usr/bin/rdm

alias check-journal="journalctl -p 3 -xb"
alias check-orphan-packages="pacman -Qtd"

function replace-string()
{
    find src/mongo \( -name "*.h" -o -name "*.cpp" \) -exec sed -i "s/$1/$2/g" {} \; -print
}
